apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-cur8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kdrj-tenant/rhtap-demo-app/hacbs-test-project-cur8@sha256:760faf71395a45356ff6a5c22ec1613745376d421bb3b6d107092be3eca70619
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
